name: "Deploy"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MEILI_MASTER_KEY: ${{ secrets.MEILI_MASTER_KEY }}
      NIX_SSHOPTS: "-o StrictHostKeyChecking=no"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: search-jerma-fans
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
    - run: nix-shell -p 'nixos-rebuild' --run "nixos-rebuild test --flake .#search-jerma-fans --target-host root@search-jerma-fans --build-host root@search-jerma-fans --verbose --fast"

